#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Task 2 / Stage 7 — Temporal Trend Analysis (unweighted baseline).

Reads the Stage-5 readability scores and reports, per publication year:
  * mean / median / SD / 95% CI of R_overall and each component (R_text, R_visual,
    R_semantic)
  * % low- and % high-readability GAs
  * RAW yearly trends and CONFOUND-ADJUSTED yearly trends
  * image-quality variables by year (resolution, OCR confidence) plotted alongside
    readability, to check whether apparent trends track technical artifacts.

ADJUSTED trends are obtained by OLS residualization: R is regressed on the confounds
ONLY (domain + publisher + log resolution + OCR confidence, year EXCLUDED), then
adjusted_R = grand_mean + residual. The yearly mean of adjusted_R therefore removes
between-year differences attributable to confound composition. This is descriptive;
the inferential mixed model is Stage 9. Use ASSOCIATION language only.

Pure numpy (no pandas). matplotlib used only for figures (guarded import).

Outputs (under OUTPUT_DIR = output/stage7_temporal_trends/):
  tables/yearly_overall.csv
  tables/yearly_components.csv
  tables/yearly_image_quality.csv
  trends/*.png                 <- all figures here, as requested
  summary.json
  report.txt
"""

import os
import csv
import json
import math
import argparse
from collections import OrderedDict, defaultdict

import numpy as np

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #
PROJECT_ROOT = "./task2_readability"
STAGE5_CSV = "output/stage5_readability_scoring/features/stage5_readability_scores.csv"
STAGE1_IMG = "output/stage1_preprocessing/image_metadata/stage1_image_metadata.csv"
STAGE2_OCR = "output/stage2_ocr_text_features/features/stage2_ocr_text_features.csv"
OUTPUT_DIR = "output/stage7_temporal_trends"

# Per-model Stage-5 readability-scores CSVs. Outputs go to OUTPUT_DIR/<model_key>/.
# Qwen uses the existing Stage-5 path; the others follow the same convention and must
# be generated by running Stage 5 per model first. Override any path as needed.
MODEL_STAGE5 = OrderedDict([
    ("qwen3_vl_32b",
     "output/stage5_readability_scoring/features/stage5_readability_scores.csv"),
    ("gemma_3_27b",
     "output/stage5_readability_scoring_gemma_3_27b/features/stage5_readability_scores.csv"),
    ("mistral_small_24b",
     "output/stage5_readability_scoring_mistral_small_24b/features/stage5_readability_scores.csv"),
])

YEAR_MIN, YEAR_MAX = 1995, 2026   # plausibility filter

# candidate column names (first match wins)
CANDS = {
    "paper_id":   ["paper_id"],
    "year":       ["publication_year", "year", "pub_year"],
    "R_overall":  ["R_overall_unweighted", "R_overall", "readability_overall", "R_G", "r_overall"],
    "R_text":     ["R_text", "r_text", "readability_text"],
    "R_visual":   ["R_visual", "r_visual", "readability_visual"],
    "R_semantic": ["R_semantic", "r_semantic", "readability_semantic"],
    "category":   ["readability_category", "R_category", "category", "readability_level"],
    "domain":     ["domain", "primary_domain", "primary_subject_area", "subject_area"],
    "publisher":  ["publisher"],
    "journal":    ["journal"],
    "ocr_conf":   ["mean_ocr_confidence", "ocr_confidence_mean", "mean_ocr_conf"],
    "pixel_count": ["pixel_count", "image_pixel_count"],
    "width":      ["width", "image_width"],
    "height":     ["height", "image_height"],
}


# --------------------------------------------------------------------------- #
# IO helpers
# --------------------------------------------------------------------------- #
def read_csv_dicts(path):
    with open(path, newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh)), csv.DictReader(open(path, encoding="utf-8")).fieldnames


def pick(header, names):
    low = {h.lower(): h for h in header}
    for n in names:
        if n in header:
            return n
        if n.lower() in low:
            return low[n.lower()]
    return None


def to_float(x):
    if x is None:
        return None
    s = str(x).strip().replace(",", "").replace("%", "")
    if s == "" or s.lower() in ("nan", "na", "none", "null", "n/a"):
        return None
    try:
        v = float(s)
        return v if v == v else None
    except (ValueError, TypeError):
        return None


def to_year(x):
    try:
        y = int(round(float(str(x).strip())))
        return y if YEAR_MIN <= y <= YEAR_MAX else None
    except (ValueError, TypeError):
        return None


def first_token(s):
    if s is None:
        return None
    s = str(s).strip()
    if not s:
        return None
    return s.split(";")[0].strip()


# --------------------------------------------------------------------------- #
# OLS residualization for adjusted trends
# --------------------------------------------------------------------------- #
def one_hot(values):
    levels = sorted({v for v in values if v not in (None, "")})
    idx = {lv: i for i, lv in enumerate(levels)}
    M = np.zeros((len(values), len(levels)), float)
    for r, v in enumerate(values):
        if v in idx:
            M[r, idx[v]] = 1.0
    return M, levels


def standardize(col):
    col = np.asarray(col, float)
    mask = ~np.isnan(col)
    if mask.sum() == 0:
        return np.zeros_like(col), np.zeros_like(col)
    mu = col[mask].mean()
    sd = col[mask].std() or 1.0
    miss = (~mask).astype(float)              # missing indicator
    filled = np.where(mask, col, mu)
    return (filled - mu) / sd, miss


def adjusted_scores(y, domain, publisher, log_res, ocr):
    n = len(y)
    Xparts = [np.ones((n, 1))]
    dm, _ = one_hot(domain); Xparts.append(dm)
    pm, _ = one_hot(publisher); Xparts.append(pm)
    z_res, _ = standardize(log_res)
    z_ocr, miss_ocr = standardize(ocr)
    Xparts.append(z_res.reshape(-1, 1))
    Xparts.append(z_ocr.reshape(-1, 1))
    Xparts.append(miss_ocr.reshape(-1, 1))
    X = np.hstack(Xparts)
    yv = np.asarray(y, float)
    beta, *_ = np.linalg.lstsq(X, yv, rcond=None)
    resid = yv - X @ beta
    return float(yv.mean()) + resid


# --------------------------------------------------------------------------- #
# Aggregation
# --------------------------------------------------------------------------- #
def yearly_stats(years, vals):
    out = OrderedDict()
    for yr in sorted(set(years)):
        v = np.array([vals[i] for i in range(len(years))
                      if years[i] == yr and vals[i] is not None and vals[i] == vals[i]], float)
        if len(v) == 0:
            continue
        n = len(v)
        sd = float(v.std(ddof=1)) if n > 1 else 0.0
        ci = 1.96 * sd / math.sqrt(n) if n > 1 else 0.0
        out[yr] = dict(n=n, mean=float(v.mean()), median=float(np.median(v)),
                       sd=sd, ci_lo=float(v.mean() - ci), ci_hi=float(v.mean() + ci))
    return out


def yearly_pct(years, cats):
    out = OrderedDict()
    for yr in sorted(set(years)):
        c = [cats[i] for i in range(len(years)) if years[i] == yr and cats[i]]
        n = len(c)
        if n == 0:
            continue
        low = sum(1 for x in c if x == "low") / n
        high = sum(1 for x in c if x == "high") / n
        out[yr] = dict(n=n, pct_low=100 * low, pct_high=100 * high)
    return out


def lin_slope(years, vals):
    x = np.array([years[i] for i in range(len(years)) if vals[i] == vals[i]], float)
    y = np.array([vals[i] for i in range(len(years)) if vals[i] == vals[i]], float)
    if len(x) < 2 or x.std() == 0:
        return float("nan")
    b = np.polyfit(x, y, 1)
    return float(b[0])   # per-year slope


# --------------------------------------------------------------------------- #
# Main
# --------------------------------------------------------------------------- #
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project-root", default=PROJECT_ROOT)
    ap.add_argument("--stage5", default=None)
    ap.add_argument("--stage1-img", default=None)
    ap.add_argument("--stage2-ocr", default=None)
    ap.add_argument("--output-dir", default=None)
    ap.add_argument("--min-year-n", type=int, default=100,
                    help="exclude years with fewer than this many GAs from trends/figures/slopes")
    ap.add_argument("--min-year", type=int, default=None,
                    help="restrict analysis to publication years >= this value (e.g. 2021)")
    ap.add_argument("--max-year", type=int, default=None,
                    help="restrict analysis to publication years <= this value (e.g. 2026)")
    ap.add_argument("--models", default=None,
                    help="comma-separated model keys to run (default: all configured). "
                         "Keys: " + ",".join(MODEL_STAGE5.keys()))
    args = ap.parse_args()
    root = args.project_root

    # build (model_key, stage5_csv) targets
    if args.stage5:                       # explicit single CSV path
        name = (args.models.split(",")[0].strip() if args.models else "custom")
        targets = [(name, args.stage5)]
    else:
        keys = ([m.strip() for m in args.models.split(",")] if args.models
                else list(MODEL_STAGE5.keys()))
        targets = [(k, os.path.join(root, MODEL_STAGE5[k])) for k in keys if k in MODEL_STAGE5]

    base_out = args.output_dir or os.path.join(root, OUTPUT_DIR)
    ran = 0
    for model_key, s5 in targets:
        out_dir = os.path.join(base_out, model_key)
        if not os.path.isfile(s5):
            print("[skip] %-18s no Stage-5 CSV at %s" % (model_key, s5))
            continue
        print("\n========== MODEL: %s ==========" % model_key)
        run_for_model(root, s5, out_dir, args)
        ran += 1
    if ran == 0:
        raise SystemExit("ERROR: no model produced output. Generate Stage 5 per model "
                         "first, or pass --stage5 <csv> --models <name>.")
    print("\n[all done] models analyzed: %d -> %s/<model>/" % (ran, base_out))


def run_for_model(root, s5, out_dir, args):
    tbl_dir = os.path.join(out_dir, "tables")
    fig_dir = os.path.join(out_dir, "trends")
    os.makedirs(tbl_dir, exist_ok=True)
    os.makedirs(fig_dir, exist_ok=True)

    rows, header = read_csv_dicts(s5)
    col = {k: pick(header, v) for k, v in CANDS.items()}
    if not col["paper_id"] or not col["year"] or not col["R_overall"]:
        raise SystemExit("ERROR: need paper_id, year, R_overall in %s (found: %s)" % (s5, col))
    print("[load] stage5 rows=%d" % len(rows))
    print("[cols] " + ", ".join("%s->%s" % (k, col[k]) for k in
          ["year", "R_overall", "R_text", "R_visual", "R_semantic",
           "category", "domain", "publisher", "ocr_conf", "pixel_count"]))
    if args.min_year is not None or args.max_year is not None:
        print("[window] restricting to years %s..%s"
              % (args.min_year if args.min_year is not None else "min",
                 args.max_year if args.max_year is not None else "max"))

    # optional joins for image quality if absent in stage5
    need_ocr = col["ocr_conf"] is None
    need_res = col["pixel_count"] is None and (col["width"] is None or col["height"] is None)
    ocr_join, res_join = {}, {}
    if need_ocr:
        p = args.stage2_ocr or os.path.join(root, STAGE2_OCR)
        if os.path.isfile(p):
            r2, h2 = read_csv_dicts(p)
            pid2 = pick(h2, ["paper_id"]); oc2 = pick(h2, CANDS["ocr_conf"])
            if pid2 and oc2:
                for r in r2:
                    ocr_join[r[pid2].strip()] = to_float(r[oc2])
                print("[join] OCR confidence from stage2 (%d)" % len(ocr_join))
    if need_res:
        p = args.stage1_img or os.path.join(root, STAGE1_IMG)
        if os.path.isfile(p):
            r1, h1 = read_csv_dicts(p)
            pid1 = pick(h1, ["paper_id"]); pc1 = pick(h1, CANDS["pixel_count"])
            w1 = pick(h1, CANDS["width"]); ht1 = pick(h1, CANDS["height"])
            for r in r1:
                pid = r[pid1].strip()
                if pc1 and to_float(r[pc1]):
                    res_join[pid] = to_float(r[pc1])
                elif w1 and ht1:
                    a, b = to_float(r[w1]), to_float(r[ht1])
                    if a and b:
                        res_join[pid] = a * b
            print("[join] resolution from stage1 (%d)" % len(res_join))

    # assemble arrays
    years, Rov, Rt, Rvi, Rse = [], [], [], [], []
    cats, dom, pub, ocr, res = [], [], [], [], []
    rt_raw_by_year = defaultdict(list)
    n_window_dropped = 0
    for r in rows:
        yr = to_year(r.get(col["year"]))
        ro = to_float(r.get(col["R_overall"]))
        if yr is None or ro is None:
            continue
        # year-window filter (min-year / max-year)
        if args.min_year is not None and yr < args.min_year:
            n_window_dropped += 1
            continue
        if args.max_year is not None and yr > args.max_year:
            n_window_dropped += 1
            continue
        pid = r[col["paper_id"]].strip()
        years.append(yr); Rov.append(ro)
        rt = to_float(r.get(col["R_text"])) if col["R_text"] else None
        rvi = to_float(r.get(col["R_visual"])) if col["R_visual"] else None
        rse = to_float(r.get(col["R_semantic"])) if col["R_semantic"] else None
        Rt.append(rt if rt is not None else float("nan"))
        Rvi.append(rvi if rvi is not None else float("nan"))
        Rse.append(rse if rse is not None else float("nan"))
        if col["R_text"]:
            rt_raw_by_year[yr].append(r.get(col["R_text"]))
        c = r.get(col["category"]) if col["category"] else None
        cats.append(str(c).strip().lower() if c else None)
        dom.append(first_token(r.get(col["domain"])) if col["domain"] else None)
        pub.append(first_token(r.get(col["publisher"])) if col["publisher"] else None)
        oc = to_float(r.get(col["ocr_conf"])) if col["ocr_conf"] else ocr_join.get(pid)
        ocr.append(oc if oc is not None else float("nan"))
        if col["pixel_count"]:
            rv = to_float(r.get(col["pixel_count"]))
        elif col["width"] and col["height"]:
            a, b = to_float(r.get(col["width"])), to_float(r.get(col["height"]))
            rv = a * b if (a and b) else None
        else:
            rv = res_join.get(pid)
        res.append(rv if rv is not None else float("nan"))

    n = len(years)
    if args.min_year is not None or args.max_year is not None:
        print("[window] dropped %d GAs outside year window; kept %d" % (n_window_dropped, n))
    print("[ready] usable GAs with year+R_overall = %d" % n)

    # ---- per-component non-null diagnostic (catches silent missingness) ---- #
    print("[diag] per-year non-null counts (year: overall/text/visual/semantic):")
    def _isnum(x):
        return x is not None and isinstance(x, float) and x == x
    for yr in sorted(set(years)):
        idx = [i for i in range(n) if years[i] == yr]
        nn = lambda arr: sum(1 for i in idx if _isnum(arr[i]))
        print("       %d: %d/%d/%d/%d" % (yr, len(idx), nn(Rt), nn(Rvi), nn(Rse)))
    # raw R_text samples for the earliest + latest kept year (decisive on missingness)
    syrs = sorted(rt_raw_by_year.keys())
    for yr in ({syrs[0], syrs[-1]} if syrs else set()):
        sample = [repr(v) for v in rt_raw_by_year[yr][:5]]
        nonempty = sum(1 for v in rt_raw_by_year[yr]
                       if v not in (None, "") and str(v).strip().lower() not in ("nan", "na", "none", "null"))
        print("[diag] R_text raw %d: nonempty=%d/%d  sample=%s"
              % (yr, nonempty, len(rt_raw_by_year[yr]), ", ".join(sample)))

    # ---- year-floor filter ---- #
    counts = defaultdict(int)
    for yr in years:
        counts[yr] += 1
    dropped = sorted([yr for yr, c in counts.items() if c < args.min_year_n])
    if dropped:
        print("[filter] dropping thin years (n < %d): %s"
              % (args.min_year_n, ", ".join("%d(n=%d)" % (yr, counts[yr]) for yr in dropped)))
        keep = [i for i in range(n) if counts[years[i]] >= args.min_year_n]
        years = [years[i] for i in keep]; Rov = [Rov[i] for i in keep]
        Rt = [Rt[i] for i in keep]; Rvi = [Rvi[i] for i in keep]; Rse = [Rse[i] for i in keep]
        cats = [cats[i] for i in keep]; dom = [dom[i] for i in keep]; pub = [pub[i] for i in keep]
        ocr = [ocr[i] for i in keep]; res = [res[i] for i in keep]
        n = len(years)
        print("[filter] remaining GAs = %d across %d years" % (n, len(set(years))))

    # category fallback: global tertiles of R_overall if no category column / values
    if not any(cats):
        q1, q2 = np.percentile([x for x in Rov], [33.333, 66.667])
        cats = ["low" if v < q1 else ("high" if v >= q2 else "medium") for v in Rov]
        print("[cat] no category column found; using global tertiles (%.4f / %.4f)" % (q1, q2))

    # adjusted overall
    log_res = [math.log1p(x) if x == x else float("nan") for x in res]
    Rov_adj = adjusted_scores(Rov, dom, pub, log_res, ocr)

    # yearly aggregates
    ys_overall = yearly_stats(years, Rov)
    ys_adj     = yearly_stats(years, list(Rov_adj))
    ys_text    = yearly_stats(years, Rt)
    ys_visual  = yearly_stats(years, Rvi)
    ys_sem     = yearly_stats(years, Rse)
    ys_pct     = yearly_pct(years, cats)
    ys_res     = yearly_stats(years, [x / 1e6 if x == x else float("nan") for x in res])  # megapixels
    ys_ocr     = yearly_stats(years, ocr)

    yrs = sorted(ys_overall.keys())

    # ---- tables ---- #
    with open(os.path.join(tbl_dir, "yearly_overall.csv"), "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["year", "n", "mean_raw", "median_raw", "sd_raw", "ci_lo_raw", "ci_hi_raw",
                    "mean_adj", "ci_lo_adj", "ci_hi_adj", "pct_low", "pct_high"])
        for yr in yrs:
            o = ys_overall[yr]; a = ys_adj.get(yr, {}); p = ys_pct.get(yr, {})
            w.writerow([yr, o["n"], "%.4f" % o["mean"], "%.4f" % o["median"], "%.4f" % o["sd"],
                        "%.4f" % o["ci_lo"], "%.4f" % o["ci_hi"],
                        "%.4f" % a.get("mean", float("nan")),
                        "%.4f" % a.get("ci_lo", float("nan")), "%.4f" % a.get("ci_hi", float("nan")),
                        "%.2f" % p.get("pct_low", float("nan")), "%.2f" % p.get("pct_high", float("nan"))])

    with open(os.path.join(tbl_dir, "yearly_components.csv"), "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["year", "n", "mean_R_text", "mean_R_visual", "mean_R_semantic",
                    "sd_R_text", "sd_R_visual", "sd_R_semantic"])
        for yr in yrs:
            t = ys_text.get(yr, {}); v = ys_visual.get(yr, {}); s = ys_sem.get(yr, {})
            w.writerow([yr, ys_overall[yr]["n"],
                        "%.4f" % t.get("mean", float("nan")), "%.4f" % v.get("mean", float("nan")),
                        "%.4f" % s.get("mean", float("nan")),
                        "%.4f" % t.get("sd", float("nan")), "%.4f" % v.get("sd", float("nan")),
                        "%.4f" % s.get("sd", float("nan"))])

    with open(os.path.join(tbl_dir, "yearly_image_quality.csv"), "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["year", "n", "mean_resolution_MP", "mean_ocr_confidence"])
        for yr in yrs:
            rr = ys_res.get(yr, {}); oo = ys_ocr.get(yr, {})
            w.writerow([yr, ys_overall[yr]["n"],
                        "%.4f" % rr.get("mean", float("nan")),
                        "%.4f" % oo.get("mean", float("nan"))])

    # ---- slopes (descriptive, associational) ---- #
    slopes = {
        "raw_overall_per_year": lin_slope(years, Rov),
        "adjusted_overall_per_year": lin_slope(years, list(Rov_adj)),
        "R_text_per_year": lin_slope(years, Rt),
        "R_visual_per_year": lin_slope(years, Rvi),
        "R_semantic_per_year": lin_slope(years, Rse),
        "resolution_MP_per_year": lin_slope(years, [x / 1e6 if x == x else float("nan") for x in res]),
        "ocr_confidence_per_year": lin_slope(years, ocr),
    }

    # ---- figures ---- #
    made = _make_figures(fig_dir, yrs, ys_overall, ys_adj, ys_text, ys_visual,
                         ys_sem, ys_pct, ys_res, ys_ocr)

    # ---- json + report ---- #
    summary = {"n_usable": n, "years": yrs, "min_year_n": args.min_year_n,
               "min_year": args.min_year, "max_year": args.max_year,
               "dropped_years": dropped, "slopes_descriptive": slopes,
               "yearly_overall": ys_overall, "yearly_overall_adjusted": ys_adj,
               "yearly_R_text": ys_text, "yearly_R_visual": ys_visual,
               "yearly_R_semantic": ys_sem, "yearly_pct": ys_pct,
               "yearly_resolution_MP": ys_res, "yearly_ocr_confidence": ys_ocr,
               "figures": made}
    with open(os.path.join(out_dir, "summary.json"), "w") as fh:
        json.dump(summary, fh, indent=2)

    with open(os.path.join(out_dir, "report.txt"), "w") as fh:
        fh.write("Task 2 / Stage 7 - Temporal Trend Analysis (unweighted baseline)\n")
        fh.write("Usable GAs: %d   Years: %d-%d\n" % (n, yrs[0], yrs[-1]))
        if args.min_year is not None or args.max_year is not None:
            fh.write("Year window: %s..%s\n"
                     % (args.min_year if args.min_year is not None else "min",
                        args.max_year if args.max_year is not None else "max"))
        if dropped:
            fh.write("Excluded thin years (n < %d): %s\n"
                     % (args.min_year_n, ", ".join(str(y) for y in dropped)))
        fh.write("\n")
        fh.write("Descriptive per-year slopes (ASSOCIATION, not causal):\n")
        for k, v in slopes.items():
            fh.write("  %-28s %s\n" % (k, _f(v)))
        fh.write("\n%-6s %6s %8s %8s %8s %8s %8s %8s %8s\n" %
                 ("year", "n", "raw", "adj", "Rtext", "Rvis", "Rsem", "%low", "%high"))
        for yr in yrs:
            o = ys_overall[yr]; a = ys_adj.get(yr, {}); t = ys_text.get(yr, {})
            v = ys_visual.get(yr, {}); s = ys_sem.get(yr, {}); p = ys_pct.get(yr, {})
            fh.write("%-6d %6d %8s %8s %8s %8s %8s %8s %8s\n" %
                     (yr, o["n"], _f(o["mean"]), _f(a.get("mean")), _f(t.get("mean")),
                      _f(v.get("mean")), _f(s.get("mean")),
                      _f(p.get("pct_low")), _f(p.get("pct_high"))))
        fh.write("\nFigures written to: %s\n" % fig_dir)
        if not made:
            fh.write("(matplotlib unavailable - tables/JSON written, figures skipped.)\n")

    print("\n[done] tables -> %s" % tbl_dir)
    print("[done] figures -> %s  (%d)" % (fig_dir, len(made)))
    print("[done] report -> %s" % os.path.join(out_dir, "report.txt"))


def _f(x):
    return "" if x is None or (isinstance(x, float) and x != x) else ("%.4f" % x)


def _series(d, key="mean"):
    return [d[yr][key] for yr in sorted(d.keys())]


def _make_figures(fig_dir, yrs, ov, adj, txt, vis, sem, pct, res, ocr):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception as e:
        print("[warn] matplotlib unavailable (%s); skipping figures." % e)
        return []
    made = []

    def save(fig, name):
        path = os.path.join(fig_dir, name)
        fig.tight_layout(); fig.savefig(path, dpi=150); plt.close(fig); made.append(name)

    # 1) overall raw vs adjusted with CI band
    fig, ax = plt.subplots(figsize=(8, 5))
    m = [ov[y]["mean"] for y in yrs]
    lo = [ov[y]["ci_lo"] for y in yrs]; hi = [ov[y]["ci_hi"] for y in yrs]
    ax.plot(yrs, m, "-o", label="raw mean")
    ax.fill_between(yrs, lo, hi, alpha=0.2, label="raw 95% CI")
    if adj:
        am = [adj[y]["mean"] for y in yrs if y in adj]
        ax.plot([y for y in yrs if y in adj], am, "-s", label="adjusted mean")
    ax.set_xlabel("publication year"); ax.set_ylabel("R_overall")
    ax.set_title("Overall readability by year (raw vs adjusted)")
    ax.legend(); ax.grid(alpha=0.3)
    save(fig, "overall_readability_by_year.png")

    # 2) components
    fig, ax = plt.subplots(figsize=(8, 5))
    for d, lab in ((txt, "R_text"), (vis, "R_visual"), (sem, "R_semantic")):
        ys = [y for y in yrs if y in d]
        ax.plot(ys, [d[y]["mean"] for y in ys], "-o", label=lab)
    ax.set_xlabel("publication year"); ax.set_ylabel("component score")
    ax.set_title("Readability components by year"); ax.legend(); ax.grid(alpha=0.3)
    save(fig, "components_by_year.png")

    # 3) % low / % high
    fig, ax = plt.subplots(figsize=(8, 5))
    ys = [y for y in yrs if y in pct]
    ax.plot(ys, [pct[y]["pct_low"] for y in ys], "-o", label="% low")
    ax.plot(ys, [pct[y]["pct_high"] for y in ys], "-o", label="% high")
    ax.set_xlabel("publication year"); ax.set_ylabel("percent of GAs")
    ax.set_title("Low / high readability share by year"); ax.legend(); ax.grid(alpha=0.3)
    save(fig, "pct_low_high_by_year.png")

    # 4) image quality twin axis
    fig, ax = plt.subplots(figsize=(8, 5))
    ys = [y for y in yrs if y in res]
    ax.plot(ys, [res[y]["mean"] for y in ys], "-o", color="tab:blue", label="resolution (MP)")
    ax.set_xlabel("publication year"); ax.set_ylabel("mean resolution (MP)", color="tab:blue")
    ax.tick_params(axis="y", labelcolor="tab:blue")
    ax2 = ax.twinx()
    yso = [y for y in yrs if y in ocr]
    ax2.plot(yso, [ocr[y]["mean"] for y in yso], "-s", color="tab:red", label="OCR confidence")
    ax2.set_ylabel("mean OCR confidence", color="tab:red")
    ax2.tick_params(axis="y", labelcolor="tab:red")
    ax.set_title("Image quality by year (artifact check)"); ax.grid(alpha=0.3)
    save(fig, "image_quality_by_year.png")

    return made


if __name__ == "__main__":
    main()